# Generated by Django 3.2.6 on 2021-08-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
