# Generated by Django 3.2.6 on 2021-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_orderplaced_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
